# Generated by Django 5.1.1 on 2026-01-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.TextField(blank=True, default='')),
                ('akar_masalah', models.TextField(blank=True, null=True)),
                ('tindakan_koreksi', models.TextField(blank=True, null=True)),
                ('level_risiko', models.CharField(blank=True, default='sedang', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('standar', models.CharField(blank=True, default='', max_length=50)),
                ('tipe', models.CharField(blank=True, default='minor', max_length=20)),
                ('status_akhir', models.CharField(blank=True, default='Terbuka', max_length=50)),
                ('rencana_tindakan', models.TextField(blank=True, null=True)),
                ('tanggal_target_rtl', models.DateField(blank=True, null=True)),
                ('bukti_rtl', models.CharField(blank=True, max_length=255, null=True)),
                ('catatan_verifikasi', models.TextField(blank=True, null=True)),
                ('status_verifikasi', models.CharField(blank=True, default='Menunggu', max_length=50)),
                ('history', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, default='', max_length=50)),
                ('unit_target', models.CharField(blank=True, default='', max_length=255)),
                ('pertanyaan', models.TextField(blank=True, default='')),
                ('bukti_wajib', models.TextField(blank=True, default='')),
                ('jawaban_auditee', models.TextField(blank=True, null=True)),
                ('doc_file', models.CharField(blank=True, max_length=255, null=True)),
                ('auditor_ids', models.JSONField(blank=True, null=True)),
                ('evaluations', models.JSONField(blank=True, null=True)),
                ('conflict', models.BooleanField(default=False)),
                ('doc_status', models.CharField(default='Belum Diunggah', max_length=50)),
                ('skor_desk', models.IntegerField(blank=True, null=True)),
                ('catatan_desk', models.TextField(blank=True, null=True)),
                ('skor_lapangan', models.IntegerField(blank=True, null=True)),
                ('catatan_lapangan', models.TextField(blank=True, null=True)),
                ('doc_note', models.TextField(blank=True, null=True)),
                ('skor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=255)),
                ('kode_unit', models.CharField(max_length=10, unique=True)),
                ('jenis_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(default='pepi123', max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='aktif', max_length=20)),
                ('assignedUnits', models.JSONField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
