# Generated by Django 5.1.1 on 2026-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(blank=True, default='', max_length=50)),
                ('pertanyaan', models.TextField(blank=True, default='')),
                ('bukti_wajib', models.TextField(blank=True, default='')),
            ],
        ),
    ]
