# Generated by Django 5.1.1 on 2026-01-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0002_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='set_type',
            field=models.CharField(choices=[('sndikti', 'Standar SNDikti'), ('unggul', 'Standar Unggul')], default='sndikti', max_length=20),
        ),
    ]
