# Generated by Django 5.1.1 on 2026-01-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0003_questionbank_set_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Perencanaan', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('auditor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor1_assignments', to='audit_app.userprofile')),
                ('auditor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor2_assignments', to='audit_app.userprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.unit')),
                ('audit_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.auditcycle')),
            ],
            options={
                'unique_together': {('audit_cycle', 'unit')},
            },
        ),
    ]
