# Generated by Django 5.1.1 on 2026-01-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0004_auditcycle_auditassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('doc_note', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.userprofile')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_app.instrument')),
            ],
            options={
                'unique_together': {('instrument', 'auditor')},
            },
        ),
    ]
