# Generated by Django 5.1.1 on 2026-01-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0006_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='standard_documents/')),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_app.userprofile')),
            ],
        ),
    ]
