# Generated by Django 5.1.1 on 2026-01-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0007_standarddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to='audit_app.userprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_assignments', to='audit_app.unit')),
            ],
            options={
                'unique_together': {('auditor', 'unit')},
            },
        ),
    ]
