# Generated by Django 5.1.1 on 2026-01-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0012_add_upm_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['standard_code', 'order']},
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='bukti_wajib',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='pertanyaan',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='set_type',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='standard',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='required_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='standard_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='standard_set',
            field=models.CharField(blank=True, choices=[('PEPI', 'Standar PEPI'), ('UNGGUL', 'Standar Unggul')], max_length=50),
        ),
    ]
