# Generated by Django 5.1.1 on 2026-01-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0013_update_questionbank_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='upmmember',
            name='division',
            field=models.CharField(blank=True, choices=[('PIMPINAN', 'Pimpinan UPM'), ('MUTU', 'Manajemen Mutu & Akreditasi'), ('MONEV', 'Monitoring dan Evaluasi'), ('TUK', 'Tempat Uji Kompetensi')], max_length=100),
        ),
        migrations.AddField(
            model_name='upmmember',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
