# Generated by Django 5.1.1 on 2026-01-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0014_add_upm_member_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upmmember',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='upmmember',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='upmmember',
            name='description',
        ),
        migrations.RemoveField(
            model_name='upmmember',
            name='position',
        ),
        migrations.AddField(
            model_name='upmmember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='audit_app.upmmember'),
        ),
        migrations.AddField(
            model_name='upmmember',
            name='role',
            field=models.CharField(blank=True, choices=[('KETUA', 'Ketua UPM'), ('SEKRETARIS', 'Sekretaris UPM'), ('KOORDINATOR', 'Koordinator'), ('ANGGOTA', 'Anggota')], max_length=50),
        ),
        migrations.AlterField(
            model_name='upmmember',
            name='division',
            field=models.CharField(blank=True, choices=[('PIMPINAN', 'Pimpinan'), ('MUTU', 'Manajemen Mutu & Akreditasi'), ('MONEV', 'Monitoring & Evaluasi'), ('TUK', 'Tempat Uji Kompetensi')], max_length=100, null=True),
        ),
    ]
