# Generated by Django 5.1.1 on 2026-01-05 03:33

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0015_update_upm_member_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upmagenda',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='upmagenda',
            name='status',
        ),
        migrations.RenameField(
            model_name='upmagenda',
            old_name='end_date',
            new_name='target_date',
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
