# Generated by Django 5.1.1 on 2026-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0016_alter_upmagenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='upmagenda',
            options={'ordering': ['start_date', 'target_date', 'id']},
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='required_evidence',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='standard_code',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='standard_set',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='bukti_wajib',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='pertanyaan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='set_type',
            field=models.CharField(choices=[('sndikti', 'Standar SNDikti'), ('unggul', 'Standar Unggul')], default='sndikti', max_length=20),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='standard',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='agenda_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('deadline', 'Deadline'), ('reminder', 'Reminder')], default='roadmap', max_length=20),
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='reminder_days_before',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='responsible_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='upmagenda',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='upm_agendas', to='audit_app.unit'),
        ),
        migrations.DeleteModel(
            name='AuditorAssignment',
        ),
    ]
