# Generated by Django 5.1.1 on 2026-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0017_alter_questionbank_options_alter_upmagenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditassignment',
            name='status',
            field=models.CharField(default='DESK_EVALUATION', max_length=50),
        ),
    ]
