# Generated by Django 5.1.1 on 2026-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0018_auditassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upmprogram',
            name='name',
            field=models.TextField(),
        ),
    ]
