# Generated by Django 5.1.1 on 2026-01-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0019_alter_upmprogram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upmagenda',
            name='agenda_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('deadline', 'Deadline'), ('reminder', 'Reminder'), ('cycle', 'Cycle'), ('cycle_event', 'Cycle Event')], default='roadmap', max_length=20),
        ),
    ]
