# Generated by Django 5.1.1 on 2026-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0020_alter_upmagenda_agenda_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='upmmember',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
