# Generated by Django 5.1.1 on 2026-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0022_alter_upmagenda_agenda_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
